version: 0.2

env:
  variables:
    MB_ARTIFACT_NAME: metabase.jar

phases:
  install:
    commands:
      - echo "Starting Install Phase"
      
      # Install Node.js 22
      - curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node.tar.xz
      - tar -xf node.tar.xz
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - node --version
      
      # Install Java 21
      - apt-get update
      - apt-get install -y openjdk-21-jdk curl wget
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      
      # Install Clojure
      - curl -O https://download.clojure.org/install/linux-install-1.11.1.1347.sh
      - chmod +x linux-install-1.11.1.1347.sh
      - ./linux-install-1.11.1.1347.sh
      - export PATH=$PATH:/usr/local/bin
      - /usr/local/bin/clojure --version
      
      # Install Yarn and dependencies
      - npm install -g yarn
      - echo "Installing Yarn dependencies..."
      - yarn install --frozen-lockfile
      
  build:
    commands:
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - export PATH=$PATH:/usr/local/bin
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      
      # Build backend JAR first (this is the critical artifact)
      - echo "Building backend JAR..."
      - ./bin/mage build
      
      # Look for JAR immediately after backend build
      - |
        TARGET_JAR=$(find . -name 'metabase*.jar' | head -n 1)
        if [ -n "$TARGET_JAR" ]; then
          echo "Backend JAR found, building frontend..."
          mv $TARGET_JAR $MB_ARTIFACT_NAME
          
          # Now build frontend (optional, since we already have the JAR)
          echo "Building frontend assets..."
          yarn build-release:cljs
          yarn build-release:js
          
          echo "Successfully created $MB_ARTIFACT_NAME with frontend assets"
        else
          echo "Error: Metabase JAR not found after backend build!"
          exit 1
        fi

artifacts:
  files:
    - $MB_ARTIFACT_NAME
    - appspec.yml 
    - deployment/**/*
  discard-paths: no
