version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
      nodejs: 22
    commands:
      - echo "[INFO] Installing dependencies..."
      - apt-get update -y
      - apt-get install -y zip git curl rlwrap
      - git init || true
      - git config --global user.email "build@example.com" || true
      - git config --global user.name "Build System" || true
      - chmod +x ./bin/build || true
      - chmod +x ./bin/mage || true
      - yarn install --network-timeout 1000000

      # === Install Clojure and add to PATH ===
      - echo "[INFO] Installing Clojure..."
      - curl -O https://download.clojure.org/install/linux-install-1.11.1.1413.sh
      - chmod +x linux-install-1.11.1.1413.sh
      - ./linux-install-1.11.1.1413.sh
      - export PATH=$PATH:/usr/local/bin
      - clojure -Sdescribe || echo "Clojure installed successfully"

  pre_build:
    commands:
      - echo "[INFO] Building frontend..."
      - yarn build:cljs
      - yarn build:js

  build:
    commands:
      - echo "[INFO] Building Metabase backend JAR..."
      - yarn mage build jar
      - ls -la target/uberjar/ || echo "JAR directory not found"
      - mkdir -p build_output
      - cp target/uberjar/metabase.jar build_output/ || echo "JAR copy failed"

  post_build:
    commands:
      - echo "[INFO] Packaging Metabase for deployment..."
      - |
        if [ ! -f build_output/metabase.jar ]; then
          echo "ERROR: metabase.jar not found! Build failed."
          exit 1
        fi
      - cd build_output
      - zip -r ../metabase-deploy.zip .
      - cd ..
      - echo "[INFO] Packaging completed successfully"
      - ls -lh metabase-deploy.zip || echo "Zip file not created"

artifacts:
  files:
    - metabase-deploy.zip
  base-directory: .
