version: 0.2

env:
  variables:
    MB_ARTIFACT_NAME: metabase.jar

phases:
  install:
    commands:
      - echo "Starting Install Phase"
      
      # Install Java 21
      - apt-get update
      - apt-get install -y openjdk-21-jdk curl wget
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      
      # Install Clojure
      - curl -O https://download.clojure.org/install/linux-install-1.11.1.1347.sh
      - chmod +x linux-install-1.11.1.1347.sh
      - ./linux-install-1.11.1.1347.sh
      - export PATH=$PATH:/usr/local/bin
      
  build:
    commands:
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - export PATH=$PATH:/usr/local/bin
      
      # Diagnostic: Check project structure
      - echo "=== Project Structure Analysis ==="
      - echo "Files in root directory:"
      - ls -la
      - echo "Build configuration files:"
      - find . -maxdepth 2 -name "build*" -o -name "project*" -o -name "deps*" -o -name "pom*" | head -10
      - echo "Bin directory contents:"
      - ls -la bin/ 2>/dev/null || echo "No bin directory"
      - echo "=== End Analysis ==="
      
      # Try common build patterns
      - echo "Attempting build methods..."
      
      # Method 1: Check for standard Metabase build
      - if [ -f "bin/build" ]; then ./bin/build; fi
      
      # Method 2: Leiningen build
      - if [ -f "project.clj" ]; then clojure -Sdeps '{:deps {leiningen/leiningen {:mvn/version "2.10.0"}}}' -M -m leiningen.core.main uberjar; fi
      
      # Method 3: Direct Clojure build
      - clojure -Sdeps '{:deps {io.github.clojure/tools.build {:git/tag "v0.9.6" :git/sha "f0c319c"}}}' -T:build uberjar :project "'metabase'" || echo "Tools.build failed"
      
      # Method 4: Check for shadow-cljs release (for full build)
      - if command -v clojure >/dev/null 2>&1; then clojure -M -m shadow.cljs.devtools.cli release app; fi
      
      # Final JAR search
      - |
        echo "=== Final JAR Search ==="
        find . -name "*.jar" 2>/dev/null | head -10
        TARGET_JAR=$(find . -name 'metabase*.jar' 2>/dev/null | head -n 1)
        
        if [ -n "$TARGET_JAR" ]; then
          echo "Found JAR: $TARGET_JAR"
          mv $TARGET_JAR $MB_ARTIFACT_NAME
          echo "Successfully created $MB_ARTIFACT_NAME"
        else
          echo "=== BUILD FAILED ==="
          echo "No JAR file produced. Available build options:"
          echo "1. Check if this is a complete Metabase fork with build capabilities"
          echo "2. Verify the build configuration files exist"
          echo "3. Consider using a pre-built Metabase JAR"
          exit 1
        fi

artifacts:
  files:
    - $MB_ARTIFACT_NAME
    - appspec.yml 
    - deployment/**/*
  discard-paths: no
