version: 0.2

env:
  variables:
    MB_ARTIFACT_NAME: metabase.jar

phases:
  install:
    commands:
      - echo "Starting Install Phase"
      
      # Install Java 21
      - apt-get update
      - apt-get install -y openjdk-21-jdk curl wget
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      
      # Install Clojure
      - curl -O https://download.clojure.org/install/linux-install-1.11.1.1347.sh
      - chmod +x linux-install-1.11.1.1347.sh
      - ./linux-install-1.11.1.1347.sh
      - export PATH=$PATH:/usr/local/bin
      - /usr/local/bin/clojure --version
      
  build:
    commands:
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - export PATH=$PATH:/usr/local/bin
      
      # Try different build approaches
      - echo "Attempting to build Metabase JAR..."
      
      # Option 1: Use Clojure build commands directly
      - clojure -T:build uberjar || echo "Clojure build failed, trying alternative..."
      
      # Option 2: Check for build scripts in the repository
      - |
        if [ -f "build.clj" ]; then
          echo "Found build.clj, running..."
          clojure -M -m build
        elif [ -f "deps.edn" ]; then
          echo "Found deps.edn, checking aliases..."
          grep -A 10 ":build" deps.edn || echo "No build alias found"
        fi
      
      # Option 3: Use the jar-download task if available (as a fallback)
      - ./bin/mage jar-download --help || echo "jar-download not available"
      
      # Option 4: Try to find existing build documentation
      - echo "Checking for build documentation..."
      - find . -name "README*" -o -name "BUILD*" -o -name "CONTRIBUTING*" | head -5
      
      # Look for the JAR file in multiple locations
      - |
        echo "Searching for JAR files..."
        find . -name "*.jar" 2>/dev/null | head -10
        TARGET_JAR=$(find . -name 'metabase*.jar' 2>/dev/null | head -n 1)
        
        if [ -z "$TARGET_JAR" ]; then 
          echo "No Metabase JAR found. Checking target directory..."
          ls -la target/ 2>/dev/null || echo "No target directory"
          echo "Build failed. Available mage tasks:"
          ./bin/mage
          exit 1
        fi
        
        mv $TARGET_JAR $MB_ARTIFACT_NAME
        echo "Successfully created $MB_ARTIFACT_NAME"

artifacts:
  files:
    - $MB_ARTIFACT_NAME
    - appspec.yml 
    - deployment/**/*
  discard-paths: no
