version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
      nodejs: 22
    commands:
      - echo "[INFO] Installing dependencies..."
      - apt-get update -y
      - apt-get install -y zip
      - yarn install

  build:
    commands:
      - echo "[INFO] Building Metabase JAR..."
      - ./bin/build
      - mkdir -p build_output
      - cp target/uberjar/metabase.jar build_output/

  post_build:
    commands:
      - echo "[INFO] Packaging Metabase for deployment..."
      - cd build_output
      - zip -r ../metabase-deploy.zip .
      - cd ..
      - ls -lh build_output || echo "Build output directory missing!"

artifacts:
  files:
    - metabase-deploy.zip
