version: 0.2

phases:
  install:
    commands:
      - echo "[INFO] === Installing dependencies ==="
      - apt-get update -y
      - apt-get install -y openjdk-17-jdk nodejs npm zip wget git curl
      - npm install -g yarn
      - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /usr/local/bin/lein
      - chmod +x /usr/local/bin/lein
      - lein --version
      - node -v && yarn -v && java -version
  pre_build:
    commands:
      - echo "[INFO] === Installing Node.js project dependencies ==="
      - yarn install --frozen-lockfile
      - echo "[INFO] === Preparing build directories ==="
      - mkdir -p build_output
  build:
    commands:
      - echo "[INFO] === Building frontend ==="
      - yarn build
      - echo "[INFO] === Building backend JAR ==="
      - lein clean
      - lein uberjar
      - echo "[INFO] === Copying build artifacts ==="
      - cp target/uberjar/metabase.jar build_output/
      - cp deployment/appspec.yml build_output/
      - cp -r deployment/scripts build_output/
      - cd build_output
      - echo "[INFO] === Creating deployment package ==="
      - zip -r metabase-deploy.zip .
  post_build:
    commands:
      - echo "[INFO] === Build completed successfully! ==="
artifacts:
  files:
    - build_output/metabase-deploy.zip
  discard-paths: yes
