version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    BUILD_DIR: "target"

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 22
    commands:
      - echo "Installing required tools..."
      - curl -O https://download.clojure.org/install/linux-install-1.11.1.1182.sh
      - chmod +x linux-install-1.11.1.1182.sh
      - ./linux-install-1.11.1.1182.sh
      - npm install -g yarn
      - echo "Environment setup complete: Java 17, Node 22, Clojure, Yarn."

  pre_build:
    commands:
      - echo "Installing frontend dependencies..."
      - yarn install --frozen-lockfile
      - echo "Building frontend..."
      - yarn run build
      - echo "Frontend build complete."

  build:
    commands:
      - echo "Building Metabase backend (JAR)..."
      - lein uberjar
      - echo "Verifying build output..."
      - ls -lh $BUILD_DIR

  post_build:
    commands:
      - echo "Metabase build completed successfully."
      - echo "Artifact path: $BUILD_DIR/metabase.jar"

artifacts:
  files:
    - target/metabase.jar
  discard-paths: yes
