version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
      nodejs: 22
    commands:
      - echo "[INFO] Installing dependencies..."
      - apt-get update -y
      - apt-get install -y zip git
      - git init || true
      - git config --global user.email "build@example.com" || true
      - git config --global user.name "Build System" || true
      - chmod +x ./bin/build || true
      - chmod +x ./bin/mage || true
      - yarn install --network-timeout 1000000

  pre_build:
    commands:
      - echo "[INFO] Preparing build environment..."
      - yarn build:cljs
      - yarn build:js

  build:
    commands:
      - echo "[INFO] Building Metabase JAR..."
      - yarn mage build jar
      - ls -la target/uberjar/ || echo "JAR directory not found"
      - mkdir -p build_output
      - cp target/uberjar/metabase.jar build_output/ || echo "JAR copy failed"

  post_build:
    commands:
      - echo "[INFO] Packaging Metabase for deployment..."
      - if [ -f build_output/metabase.jar ]; then
          echo "JAR found, packaging...";
          cd build_output;
          zip -r ../metabase-deploy.zip .;
          cd ..;
          echo "Packaging completed successfully";
        else
          echo "ERROR: metabase.jar not found! Build failed.";
          exit 1;
        fi
      - ls -lh metabase-deploy.zip || echo "Zip file not created"

artifacts:
  files:
    - metabase-deploy.zip
  base-directory: .
