version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo "[INFO] Installing dependencies..."
      - apt-get update -y
      - apt-get install -y zip clojure
      - npm install -g yarn
  pre_build:
    commands:
      - echo "[INFO] Preparing frontend and backend..."
      - mkdir -p build_output
  build:
    commands:
      - echo "[INFO] Building frontend..."
      - yarn install
      - yarn build

      - echo "[INFO] Building backend..."
      - ./bin/build-drivers.sh
      - clojure -M:run

      - echo "[INFO] Packaging build artifact..."
      - cp -r target build_output/ || true
      - cp -r resources build_output/ || true
      - cp appspec.yml build_output/
      - cp -r scripts build_output/
      - cd build_output
      - zip -r metabase-deploy.zip .
  post_build:
    commands:
      - echo "[INFO] Build complete. Artifact ready for upload."
artifacts:
  files:
    - build_output/metabase-deploy.zip
  discard-paths: yes
