version: 0.2

env:
  variables:
    MB_ARTIFACT_NAME: metabase.jar

phases:
  install:
    commands:
      - echo "Starting Install Phase"
      
      # Install Node.js 22
      - curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node.tar.xz
      - tar -xf node.tar.xz
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - node --version
      
      # Install Java 21
      - apt-get update
      - apt-get install -y openjdk-21-jdk curl wget
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      
      # Install Clojure 
      - curl -O https://download.clojure.org/install/linux-install-1.11.1.1347.sh
      - chmod +x linux-install-1.11.1.1347.sh
      - ./linux-install-1.11.1.1347.sh
      - export PATH=$PATH:/usr/local/bin
      - /usr/local/bin/clojure --version
      
      # Install Yarn and dependencies
      - npm install -g yarn
      - echo "Installing Yarn dependencies..."
      - yarn install --frozen-lockfile
      
  build:
    commands:
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - export PATH=$PATH:/usr/local/bin
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      
      # Use the proper build scripts from the bin directory
      - echo "Using Metabase build scripts..."
      - chmod +x ./bin/*
      
      # Option 1: Try the main build script
      - ./bin/build || echo "bin/build failed, trying alternative..."
      
      # Option 2: Try build.sh
      - ./bin/build.sh || echo "build.sh failed, trying build-for-test..."
      
      # Option 3: Try build-for-test (often works for production too)
      - ./bin/build-for-test || echo "build-for-test failed"
      
      # Look for the JAR file
      - |
        echo "Searching for built JAR..."
        find . -name "*.jar" 2>/dev/null | head -10
        TARGET_JAR=$(find . -name 'metabase*.jar' 2>/dev/null | head -n 1)
        
        if [ -n "$TARGET_JAR" ]; then
          echo "Found JAR: $TARGET_JAR"
          mv $TARGET_JAR $MB_ARTIFACT_NAME
          echo "Successfully created $MB_ARTIFACT_NAME"
        else
          echo "No JAR found after build attempts"
          echo "Trying to understand build process from documentation..."
          cat bin/build-mb.md 2>/dev/null || echo "No build documentation found"
          exit 1
        fi

artifacts:
  files:
    - $MB_ARTIFACT_NAME
    - appspec.yml 
    - scripts/**/*
  discard-paths: no
