version: 0.2

env:
  variables:
    MB_ARTIFACT_NAME: metabase.jar

phases:
  install:
    commands:
      - echo "Starting Install Phase"
      
      # Install Node.js 22
      - curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node.tar.xz
      - tar -xf node.tar.xz
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - node --version
      
      # Install Java 21
      - apt-get update
      - apt-get install -y openjdk-21-jdk curl wget
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      
      # Install Clojure
      - curl -O https://download.clojure.org/install/linux-install-1.11.1.1347.sh
      - chmod +x linux-install-1.11.1.1347.sh
      - ./linux-install-1.11.1.1347.sh
      - export PATH=$PATH:/usr/local/bin
      - /usr/local/bin/clojure --version
      
      # Install Yarn and dependencies
      - npm install -g yarn
      - echo "Installing Yarn dependencies..."
      - yarn install --frozen-lockfile
      
      # Install missing dependency
      - echo "Installing missing react-beautiful-dnd..."
      - yarn add react-beautiful-dnd
      
  build:
    commands:
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - export PATH=$PATH:/usr/local/bin
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      
      # Make build scripts executable
      - echo "Setting execute permissions on build scripts..."
      - chmod +x ./bin/*
      - ls -la ./bin/
      
      # Build frontend (this succeeded in your last attempt)
      - echo "Building Metabase frontend..."
      - yarn build

      # Option 1: Try the build script with explicit bash
      - echo "Building complete Metabase JAR using bash..."
      - bash ./bin/build
      
      # If Option 1 fails, try Option 2: Use Clojure directly
      - |
        if [ ! -f "target/uberjar/metabase.jar" ]; then
          echo "Build script failed, trying Clojure build directly..."
          clojure -T:build uberjar :project-oss true
        fi
      
      # Find and rename the JAR
      - |
        echo "Searching for built JAR..."
        TARGET_JAR=$(find . -name 'metabase*.jar' -not -name '*standalone*' -not -name '*original*' 2>/dev/null | head -n 1)
        
        if [ -n "$TARGET_JAR" ]; then
          echo "Found JAR: $TARGET_JAR"
          mv "$TARGET_JAR" "$MB_ARTIFACT_NAME"
          echo "Successfully created $MB_ARTIFACT_NAME"
          
          # Verify the JAR contains frontend resources
          echo "Verifying JAR contents..."
          jar tf "$MB_ARTIFACT_NAME" | head -10
        else
          echo "Error: No JAR file found after build!"
          find . -name '*.jar' -type f
          exit 1
        fi

artifacts:
  files:
    - $MB_ARTIFACT_NAME
    - appspec.yml 
    - deployment/**/*
  discard-paths: no
