version: 0.2

env:
  variables:
    MB_ARTIFACT_NAME: metabase.jar

phases:
  install:
    commands:
      - echo "Starting Install Phase"
      
      # Install Node.js 22
      - curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node.tar.xz
      - tar -xf node.tar.xz
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - node --version
      
      # Install Java 21
      - apt-get update
      - apt-get install -y openjdk-21-jdk curl wget
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      
      # Install Clojure
      - curl -O https://download.clojure.org/install/linux-install-1.11.1.1347.sh
      - chmod +x linux-install-1.11.1.1347.sh
      - ./linux-install-1.11.1.1347.sh
      - export PATH=$PATH:/usr/local/bin
      - /usr/local/bin/clojure --version
      
      # Install Yarn and dependencies
      - npm install -g yarn
      - echo "Installing Yarn dependencies..."
      - yarn install --frozen-lockfile
      
  build:
    commands:
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - export PATH=$PATH:/usr/local/bin
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      
      # Build frontend assets first
      - echo "Building frontend assets..."
      - yarn build-release:cljs
      - yarn build-release:js
      
      # Try different backend build methods
      - echo "Attempting to build backend JAR..."
      - |
        # Try mage first
        if [ -f "./bin/mage" ]; then
          echo "Using mage build tool..."
          ./bin/mage build
        else
          echo "Mage not found, trying Clojure build commands..."
          # Try various Clojure build commands
          clojure -T:build uberjar || \
          clojure -X:build:build || \
          clojure -M:build:build || \
          echo "All build methods failed"
        fi
      
      # Search for JAR in multiple locations
      - |
        echo "Searching for built JAR file..."
        find . -name "*.jar" 2>/dev/null | grep -v node_modules | head -10
        TARGET_JAR=$(find . -name 'metabase*.jar' 2>/dev/null | grep -v node_modules | head -n 1)
        if [ -z "$TARGET_JAR" ]; then 
          TARGET_JAR=$(find target/ -name '*.jar' 2>/dev/null | head -n 1)
        fi
        if [ -z "$TARGET_JAR" ]; then 
          echo "Error: No JAR file found after build!"
          echo "Directory structure:"
          ls -la
          echo "Target directory contents:"
          ls -la target/ 2>/dev/null || echo "No target directory"
          exit 1
        fi
        echo "Found JAR: $TARGET_JAR"
        mv $TARGET_JAR $MB_ARTIFACT_NAME
        echo "Successfully created and renamed $MB_ARTIFACT_NAME"

artifacts:
  files:
    - $MB_ARTIFACT_NAME
    - appspec.yml 
    - deployment/**/*
  discard-paths: no
