version: 0.2

phases:
  install:
    commands:
      - echo "[INFO] Installing dependencies..."
      - apt-get update -y
      - apt-get install -y openjdk-11-jdk git zip wget
      - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /usr/local/bin/lein
      - chmod +x /usr/local/bin/lein
  pre_build:
    commands:
      - echo "[INFO] Preparing build environment..."
      - mkdir -p build_output
  build:
    commands:
      - echo "[INFO] Building Metabase JAR from source..."
      - lein clean
      - lein uberjar
      - echo "[INFO] Copying build artifacts..."
      - cp target/uberjar/metabase.jar build_output/
      - cp deployment/appspec.yml build_output/
      - cp -r deployment/scripts build_output/
      - cd build_output
      - echo "[INFO] Creating deployment archive..."
      - zip -r metabase-deploy.zip .
  post_build:
    commands:
      - echo "[INFO] Build complete."
artifacts:
  files:
    - build_output/metabase-deploy.zip
  discard-paths: yes
