version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "[INFO] Installing system dependencies..."
      - apt-get update -y
      - apt-get install -y openjdk-17-jdk clojure zip
      - java -version
      - clojure -Sdescribe | grep version || echo "Clojure installed"

  build:
    commands:
      - echo "[INFO] Building backend JAR..."
      - ./bin/build-drivers.sh
      - echo "[INFO] Creating deployment package..."
      - mkdir -p build_output
      - cp metabase.jar appspec.yml -t build_output/
      - cp -r scripts build_output/
      - cd build_output && zip -r metabase-deploy.zip .

artifacts:
  files:
    - build_output/metabase-deploy.zip
  discard-paths: yes
