version: 0.2

env:
  variables:
    MB_ARTIFACT_NAME: metabase.jar
    ARTIFACT_DIR: artifacts

phases:
  install:
    commands:
      - echo "===== INSTALL PHASE STARTED ====="

      # Install dependencies
      - apt-get update -y
      - apt-get install -y curl wget xz-utils openjdk-21-jdk

      # Setup environment variables
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version

      # Install Node.js 22
      - echo "Installing Node.js 22..."
      - curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node.tar.xz
      - tar -xf node.tar.xz
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - node --version

      # Install Clojure
      - echo "Installing Clojure..."
      - curl -O https://download.clojure.org/install/linux-install-1.11.1.1347.sh
      - chmod +x linux-install-1.11.1.1347.sh
      - ./linux-install-1.11.1.1347.sh
      - export PATH=$PATH:/usr/local/bin
      - clojure -Sdescribe || echo "Clojure installed"

      # Install Yarn if package.json exists
      - if [ -f package.json ]; then
          npm install -g yarn;
          echo "Installing Yarn dependencies...";
          yarn install --frozen-lockfile;
        else
          echo "No package.json found, skipping Yarn install.";
        fi

  build:
    commands:
      - echo "===== BUILD PHASE STARTED ====="
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - export PATH=$PATH:/usr/local/bin
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH

      # Build Metabase JAR
      - echo "Building Metabase JAR using build-for-test..."
      - ./bin/build-for-test

      # Locate and prepare JAR
      - mkdir -p $ARTIFACT_DIR
      - |
        echo "Searching for built JAR..."
        TARGET_JAR=$(find . -type f -name 'metabase*.jar' | head -n 1)
        if [ -n "$TARGET_JAR" ]; then
          echo "Found JAR: $TARGET_JAR"
          mv "$TARGET_JAR" "$ARTIFACT_DIR/$MB_ARTIFACT_NAME"
          echo "Moved JAR to $ARTIFACT_DIR/$MB_ARTIFACT_NAME"
        else
          echo "Error: No JAR file found after build!"
          exit 1
        fi

artifacts:
  files:
    - artifacts/*
    - appspec.yml
    - scripts/**/*
  discard-paths: no

cache:
  paths:
    - ~/.m2/**/*    # Clojure/maven cache
    - ~/.yarn-cache/**/*    # Yarn cache
