version: 0.2

env:
  variables:
    MB_ARTIFACT_NAME: metabase.jar

phases:
  install:
    commands:
      - echo "Starting Install Phase"
      
      # Install Node.js 22
      - curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node.tar.xz
      - tar -xf node.tar.xz
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - node --version
      
      # Install Java and Clojure
      - yum update -y
      - yum install -y java-11-amazon-corretto-devel
      # Install Clojure tools
      - curl -O https://download.clojure.org/install/clojure-tools-1.11.1.1347.tar.gz
      - mkdir -p /usr/local/lib/clojure
      - tar xzf clojure-tools-1.11.1.1347.tar.gz -C /usr/local/lib/clojure
      - ln -s /usr/local/lib/clojure/clojure-tools-1.11.1.1347/bin/clojure /usr/local/bin/clojure
      - ln -s /usr/local/lib/clojure/clojure-tools-1.11.1.1347/bin/clj /usr/local/bin/clj
      
      # Verify installation
      - clojure --version
      
      # Install Yarn and dependencies
      - npm install -g yarn
      - echo "Installing Yarn dependencies..."
      - yarn install --frozen-lockfile
      
  build:
    commands:
      - export PATH=$(pwd)/node-v22.11.0-linux-x64/bin:$PATH
      - echo "Starting Metabase full release build..."
      - yarn build-release
      - |
        TARGET_JAR=$(find target/ -name 'metabase*.jar' | head -n 1)
        if [ -z "$TARGET_JAR" ]; then 
          echo "Error: Metabase JAR not found after release build!"
          exit 1
        fi
        mv $TARGET_JAR $MB_ARTIFACT_NAME
        echo "Successfully created and renamed $MB_ARTIFACT_NAME"

artifacts:
  files:
    - $MB_ARTIFACT_NAME
    - appspec.yml 
    - deployment/**/*
  discard-paths: no
