version: 0.2

env:
  variables:
    MB_ARTIFACT_NAME: metabase.jar
  compute-type: BUILD_GENERAL1_LARGE  # Use at least large (7 GB RAM)
  shell: bash

phases:
  install:
    runtime-versions:
      java: corretto21
      nodejs: 22
    commands:
      - echo "=== INSTALL PHASE STARTED ==="
      - apt-get update -y
      - apt-get install -y git curl wget xz-utils build-essential
      - echo "Java version:"
      - java -version
      - echo "Node version:"
      - node --version
      - npm install -g yarn
      - yarn --version

      # Install Clojure
      - curl -O https://download.clojure.org/install/linux-install-1.11.1.1347.sh
      - chmod +x linux-install-1.11.1.1347.sh
      - ./linux-install-1.11.1.1347.sh
      - clojure -Sdescribe

  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - git rev-parse --short HEAD || echo "Warning: no git commit detected"
      - ls -lah
      - chmod +x bin/* || true

  build:
    commands:
      - echo "=== BUILDING METABASE ==="
      - ./bin/build || ./bin/build.sh || ./bin/build-for-test
      - echo "=== Searching for built jar ==="
      - find ./target -name "*.jar" | head -n 5
      - TARGET_JAR=$(find ./target -name 'metabase*.jar' | head -n 1)
      - if [ -n "$TARGET_JAR" ]; then
          echo "Found JAR: $TARGET_JAR";
          mv "$TARGET_JAR" "$MB_ARTIFACT_NAME";
        else
          echo "No JAR found. Build failed.";
          exit 1;
        fi

  post_build:
    commands:
      - echo "=== POST BUILD ==="
      - ls -lah

artifacts:
  files:
    - metabase.jar
    - appspec.yml
    - scripts/**/*
  discard-paths: no
