version: 0.2

# Define environment variables
env:
  variables:
    MB_ARTIFACT_NAME: metabase.jar

phases:
  install:
    commands:
      - echo "Starting Install Phase"
      - npm install -g yarn
      - echo "Installing Yarn dependencies..."
      - yarn install --frozen-lockfile
      
  build:
    commands:
      - echo "Starting Metabase full release build..."
      - yarn build-release
      - |
        TARGET_JAR=$(find target/ -name 'metabase*.jar' | head -n 1)
        if [ -z "$TARGET_JAR" ]; then 
          echo "Error: Metabase JAR not found after release build!"
          exit 1
        fi
        mv $TARGET_JAR $MB_ARTIFACT_NAME
        echo "Successfully created and renamed $MB_ARTIFACT_NAME"

artifacts:
  files:
    - $MB_ARTIFACT_NAME
    - appspec.yml 
    - deployment/**/*
  discard-paths: no
